In [1]:
import torch 
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import numpy as np
from itertools import permutations 
import sys
base = '/home3/ebrahim/isr/'
sys.path.append(base)
from RNNcell import RNN_one_layer, RNN_two_layers
from sklearn.linear_model import LogisticRegression, Ridge
from sklearn.preprocessing import OneHotEncoder
from sklearn.metrics import r2_score
from matplotlib import pyplot as plt
from skimage.measure import block_reduce
from scipy.stats import pearsonr
import pandas as pd
import seaborn as sns
import pickle


In [3]:
torch.log(torch.Tensor([0]))

tensor([-inf])

In [54]:
# Step 1) Create predictors for ridge regression model
letters = np.arange(4)
list_length = 3
X_p = permutations(letters, list_length)
X_reg = []
for x in X_p:
    X_reg.append(x)
X_reg = np.stack(X_reg)

enc = OneHotEncoder(sparse=False)
X_transform = enc.fit_transform(X_reg)

# Step 2) Create synthetic y variables for ridge regression model 

pos_enc = np.vstack((X_reg.shape[0], ))



[[0 1 2]
 [0 1 3]
 [0 2 1]
 [0 2 3]
 [0 3 1]]
[[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]]


In [41]:
def synthetic_y(X):
    y_arr = []
    for trial in X:
        for i, item in enumerate(trial):
            y_arr.append([i, item])
    return y_arr

In [42]:
y_arr = synthetic_y(X)
print(len(y_arr))


480


(120, 40)
